// Fairyteller — данные всех работ.
// slug используется как ключ лайков в Supabase (artwork_likes.slug).
// showcase: true — работа попадает в блок "Избранное" на главной.
// accent — акцентный цвет неоновой рамки showcase-работы ("gold" | "cyan"): рамка
//   подсвечивается только у той работы, что сейчас показана в hero-баннере, и уголки
//   баннера перекрашиваются в этот же цвет синхронно со сменой слайда.
// dateAdded — дата ВЫКЛАДКИ на сайт (для бейджа NEW, 14 дней). Формат YYYY-MM-DD.
// w/h — размеры preview для сохранения пропорций в masonry (без скачков вёрстки).

const WORKS = [
  {
    slug: "01-ink-and-tenderness",
    title: { ru: "Чернила и нежность", en: "Ink and Tenderness" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: true,
    accent: "gold",
    dateAdded: "2026-06-30",
    w: 800, h: 448,
  },
  {
    slug: "02-sight-through-the-wires",
    title: { ru: "Взгляд сквозь провода", en: "Sight Through the Wires" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: true,
    accent: "cyan",
    dateAdded: "2026-06-30",
    w: 800, h: 533,
  },
  {
    slug: "03-solar-wind",
    title: { ru: "Солнечный ветер", en: "Solar Wind" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: true,
    accent: "gold",
    dateAdded: "2026-06-30",
    w: 800, h: 533,
  },
  {
    slug: "04-old-rebels",
    title: { ru: "Старые бунтари", en: "Old Rebels" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: true,
    accent: "cyan",
    dateAdded: "2026-06-30",
    w: 800, h: 600,
  },
  {
    slug: "05-midnight-bar",
    title: { ru: "Полночный бар", en: "Midnight Bar" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 667, h: 1000,
  },
  {
    slug: "06-wasteland-wanderer",
    title: { ru: "Странник пустошей", en: "Wasteland Wanderer" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 800, h: 533,
  },
  {
    slug: "07-neon-date",
    title: { ru: "Свидание в неоне", en: "Neon Date" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 753, h: 1000,
  },
  {
    slug: "08-yellow-racer",
    title: { ru: "Жёлтый гонщик", en: "Yellow Racer" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 800, h: 600,
  },
  {
    slug: "09-street-chic",
    title: { ru: "Уличный шик", en: "Street Chic" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 336, h: 1000,
  },
  {
    slug: "10-by-the-water",
    title: { ru: "У воды", en: "By the Water" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 560, h: 1000,
  },
  {
    slug: "11-garage-punk",
    title: { ru: "Гаражный панк", en: "Garage Punk" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 560, h: 1000,
  },
  {
    slug: "12-golden-patterns",
    title: { ru: "Золотые узоры", en: "Golden Patterns" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 667, h: 1000,
  },
  {
    slug: "13-neon-fighter",
    title: { ru: "Боец из неона", en: "Neon Fighter" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 753, h: 1000,
  },
  {
    slug: "14-dance-of-lanterns",
    title: { ru: "Танец фонарей", en: "Dance of Lanterns" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 753, h: 1000,
  },
  {
    slug: "15-apprentice-witch",
    title: { ru: "Ученица чародейки", en: "The Apprentice Witch" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 753, h: 1000,
  },
  {
    slug: "16-beasts-smile",
    title: { ru: "Улыбка зверя", en: "The Beast's Smile" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 753, h: 1000,
  },
  {
    slug: "17-street-pattern",
    title: { ru: "Уличный узор", en: "Street Pattern" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 475, h: 1000,
  },
  {
    slug: "18-sunset-laughter",
    title: { ru: "Смех на закате", en: "Sunset Laughter" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 560, h: 1000,
  },
  {
    slug: "19-wedding-among-airships",
    title: { ru: "Свадьба среди дирижаблей", en: "Wedding Among Airships" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 560, h: 1000,
  },
  {
    slug: "20-rooftops-of-the-megacity",
    title: { ru: "Крыши мегаполиса", en: "Rooftops of the Megacity" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-02",
    w: 800, h: 533,
  },
  {
    slug: "21-fireflies-and-roses",
    title: { ru: "Светлячки и розы", en: "Fireflies and Roses" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 753, h: 1000,
  },
  {
    slug: "22-sunlit-heights",
    title: { ru: "Солнечные высоты", en: "Sunlit Heights" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 753, h: 1000,
  },
  {
    slug: "23-keeper-of-potions",
    title: { ru: "Хранительница зелий", en: "Keeper of Potions" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 753, h: 1000,
  },
  {
    slug: "24-queen-of-ravens",
    title: { ru: "Королева воронов", en: "Queen of Ravens" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 753, h: 1000,
  },
  {
    slug: "25-night-bazaar",
    title: { ru: "Ночной базар", en: "Night Bazaar" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 753, h: 1000,
  },
  {
    slug: "26-bazaar-rogue",
    title: { ru: "Плутовка с рынка", en: "Bazaar Rogue" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 667, h: 1000,
  },
  {
    slug: "27-the-hound-whisperer",
    title: { ru: "Повелительница псов", en: "The Hound Whisperer" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "28-saffron-dance",
    title: { ru: "Шафрановый танец", en: "Saffron Dance" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "29-dandelion-spirit",
    title: { ru: "Дух одуванчика", en: "Dandelion Spirit" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "30-feathered-priestess",
    title: { ru: "Пернатая жрица", en: "Feathered Priestess" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "31-troubadours-song",
    title: { ru: "Песнь трубадура", en: "Troubadour's Song" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 667, h: 1000,
  },
  {
    slug: "32-wildflower-princess",
    title: { ru: "Принцесса полевых цветов", en: "Wildflower Princess" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "33-secrets-in-velvet",
    title: { ru: "Тайны в бархате", en: "Secrets in Velvet" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "34-smoke-and-marble",
    title: { ru: "Дым и мрамор", en: "Smoke and Marble" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 753, h: 1000,
  },
  {
    slug: "35-rebel-in-pink",
    title: { ru: "Розовая бунтарка", en: "Rebel in Pink" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 753, h: 1000,
  },
  {
    slug: "36-graffiti-dance",
    title: { ru: "Граффити-танец", en: "Graffiti Dance" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "37-bar-under-lanterns",
    title: { ru: "Бар среди фонарей", en: "Bar Under Lanterns" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "38-neon-smoke",
    title: { ru: "Неоновый дым", en: "Neon Smoke" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "39-champagne-nights",
    title: { ru: "Шампанские ночи", en: "Champagne Nights" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "40-timeout",
    title: { ru: "Тайм-аут", en: "Timeout" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "41-stadium-evening",
    title: { ru: "Вечер на стадионе", en: "Stadium Evening" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "42-sideline-smile",
    title: { ru: "Улыбка с трибуны", en: "Sideline Smile" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "43-gold-and-graffiti",
    title: { ru: "Золото и граффити", en: "Gold and Graffiti" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-08",
    w: 560, h: 1000,
  },
  {
    slug: "44-lights-over-the-canals",
    title: { ru: "Огни над каналами", en: "Lights Over the Canals" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 533,
  },
  {
    slug: "45-midnight-alchemy",
    title: { ru: "Алхимия полуночи", en: "Midnight Alchemy" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 533,
  },
  {
    slug: "46-bloom-in-profile",
    title: { ru: "Цветочный профиль", en: "Bloom in Profile" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 533,
  },
  {
    slug: "47-cherry-blossom-silk",
    title: { ru: "Сакура и шёлк", en: "Cherry Blossom Silk" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "48-light-between-the-pages",
    title: { ru: "Свет между страниц", en: "Light Between the Pages" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "49-greenhouse-whisper",
    title: { ru: "Оранжерейный шёпот", en: "Greenhouse Whisper" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 533,
  },
  {
    slug: "50-the-witchs-shop",
    title: { ru: "Ведьмина лавка", en: "The Witch's Shop" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 667, h: 1000,
  },
  {
    slug: "51-winter-guest",
    title: { ru: "Зимняя гостья", en: "Winter Guest" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 753, h: 1000,
  },
  {
    slug: "52-road-to-the-castle",
    title: { ru: "Дорога к замку", en: "Road to the Castle" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "53-lantern-and-scales",
    title: { ru: "Фонарь и чешуя", en: "Lantern and Scales" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 753, h: 1000,
  },
  {
    slug: "54-priest-of-the-swamp-temple",
    title: { ru: "Жрец болотного храма", en: "Priest of the Swamp Temple" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "55-flame-chieftain",
    title: { ru: "Огненный вождь", en: "Flame Chieftain" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "56-snowbound-sorrow",
    title: { ru: "Снежная печаль", en: "Snowbound Sorrow" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "57-butterflies-on-the-corset",
    title: { ru: "Бабочки на корсете", en: "Butterflies on the Corset" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "58-tea-ceremony-of-shadows",
    title: { ru: "Чайная церемония теней", en: "Tea Ceremony of Shadows" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "59-the-tavern-cat",
    title: { ru: "Кот трактирщик", en: "The Tavern Cat" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "60-carnival-under-the-parasol",
    title: { ru: "Карнавал под зонтом", en: "Carnival Under the Parasol" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 753, h: 1000,
  },
  {
    slug: "61-child-of-the-hearth",
    title: { ru: "Дитя очага", en: "Child of the Hearth" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "62-queen-of-skulls",
    title: { ru: "Королева черепов", en: "Queen of Skulls" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "63-nomads-gaze",
    title: { ru: "Взгляд кочевника", en: "Nomad's Gaze" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "64-white-plume",
    title: { ru: "Белое перо", en: "White Plume" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "65-wanderer-of-the-sands",
    title: { ru: "Странник песков", en: "Wanderer of the Sands" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "66-the-pumpkin-king",
    title: { ru: "Тыквоголовый король", en: "The Pumpkin King" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "67-golden-idol",
    title: { ru: "Золотой идол", en: "Golden Idol" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 753, h: 1000,
  },
  {
    slug: "68-night-walk-with-a-cat",
    title: { ru: "Ночная прогулка с котом", en: "Night Walk with a Cat" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "69-under-the-yellow-moon",
    title: { ru: "Под жёлтой луной", en: "Under the Yellow Moon" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "70-tea-among-the-clouds",
    title: { ru: "Чаепитие в облаках", en: "Tea Among the Clouds" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "71-gathering-of-shades",
    title: { ru: "Собрание теней", en: "Gathering of Shades" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 448,
  },
  {
    slug: "72-riding-the-polar-bear",
    title: { ru: "Верхом на белом медведе", en: "Riding the Polar Bear" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "73-pink-curls-and-rabbits",
    title: { ru: "Розовые кудри и кролики", en: "Pink Curls and Rabbits" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "74-house-among-the-roots",
    title: { ru: "Домик среди корней", en: "House Among the Roots" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "75-cat-on-the-crescent",
    title: { ru: "Кошка на полумесяце", en: "Cat on the Crescent" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "76-elder-of-the-garden",
    title: { ru: "Садовый старейшина", en: "Elder of the Garden" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "77-hollow-in-crimson",
    title: { ru: "Дупло в багрянце", en: "Hollow in Crimson" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "78-woodcutter-and-the-black-cat",
    title: { ru: "Дровосек и чёрный кот", en: "Woodcutter and the Black Cat" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "79-spirit-of-blooming-fields",
    title: { ru: "Дух цветущих полей", en: "Spirit of Blooming Fields" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "80-cat-at-the-bar",
    title: { ru: "Кот у барной стойки", en: "Cat at the Bar" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 753, h: 1000,
  },
  {
    slug: "81-street-rhythm",
    title: { ru: "Уличный ритм", en: "Street Rhythm" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "82-garden-picnic",
    title: { ru: "Пикник в саду", en: "Garden Picnic" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "83-pink-bob-punk",
    title: { ru: "Панк с розовым каре", en: "Pink Bob Punk" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 753, h: 1000,
  },
  {
    slug: "84-peace-and-love-sign",
    title: { ru: "Знак мира и любви", en: "Peace and Love Sign" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "85-cheetahs-companion",
    title: { ru: "Спутница гепарда", en: "Cheetah's Companion" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "86-doll-bows",
    title: { ru: "Кукольные бантики", en: "Doll Bows" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "87-cigarette-at-the-bar",
    title: { ru: "Сигарета у стойки", en: "Cigarette at the Bar" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "88-smoke-over-the-ocean",
    title: { ru: "Дым над океаном", en: "Smoke Over the Ocean" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 753, h: 1000,
  },
  {
    slug: "89-bikers-on-the-subway",
    title: { ru: "Байкеры в метро", en: "Bikers on the Subway" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 753, h: 1000,
  },
  {
    slug: "90-midnight-subway",
    title: { ru: "Полночная электричка", en: "Midnight Subway" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "91-dance-in-a-floral-dress",
    title: { ru: "Танец в цветочном платье", en: "Dance in a Floral Dress" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 560, h: 1000,
  },
  {
    slug: "92-evening-with-a-lantern",
    title: { ru: "Вечер с фонарём", en: "Evening with a Lantern" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 753, h: 1000,
  },
  {
    slug: "93-wandering-farmer",
    title: { ru: "Странствующий фермер", en: "Wandering Farmer" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "94-the-gearwork-postman",
    title: { ru: "Почтальон в шестерёнках", en: "The Gearwork Postman" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "95-bird-on-the-shoulder",
    title: { ru: "Птица на плече", en: "Bird on the Shoulder" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "96-the-content-innkeeper",
    title: { ru: "Довольный трактирщик", en: "The Content Innkeeper" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "97-knight-at-rest",
    title: { ru: "Рыцарь на покое", en: "Knight at Rest" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "98-lady-with-a-cigarette",
    title: { ru: "Дама с сигаретой", en: "Lady with a Cigarette" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "99-the-victorian-merchant",
    title: { ru: "Торговец из Викторианской эпохи", en: "The Victorian Merchant" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "100-the-cook-and-his-pots",
    title: { ru: "Повар и его котелки", en: "The Cook and His Pots" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "101-a-ghost-behind-him",
    title: { ru: "Призрак за спиной", en: "A Ghost Behind Him" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "102-the-dragons-rest",
    title: { ru: "Отдых дракона", en: "The Dragon's Rest" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "103-the-cat-hitmen",
    title: { ru: "Котокиллеры", en: "The Cat Hitmen" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "104-pointing-finger",
    title: { ru: "Указующий перст", en: "Pointing Finger" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "105-ronin-in-a-golden-halo",
    title: { ru: "Ронин в золотом ореоле", en: "Ronin in a Golden Halo" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 753, h: 1000,
  },
  {
    slug: "106-the-golden-oracle",
    title: { ru: "Золотой оракул", en: "The Golden Oracle" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 753, h: 1000,
  },
  {
    slug: "107-patterned-android",
    title: { ru: "Узорчатый андроид", en: "Patterned Android" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 753, h: 1000,
  },
  {
    slug: "108-smile-of-the-mechanical-demon",
    title: { ru: "Улыбка механического демона", en: "Smile of the Mechanical Demon" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "109-golden-priestess",
    title: { ru: "Золотая жрица", en: "Golden Priestess" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "110-fangs-of-steel",
    title: { ru: "Клыки из стали", en: "Fangs of Steel" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "111-steel-veil",
    title: { ru: "Стальная вуаль", en: "Steel Veil" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "112-chained-lips",
    title: { ru: "Скованные уста", en: "Chained Lips" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-12",
    w: 800, h: 1000,
  },
  {
    slug: "113-tea-time-serenade",
    title: { ru: "Серенада за чаем", en: "Tea-Time Serenade" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 753, h: 1000,
  },
  {
    slug: "114-nap-in-a-cup",
    title: { ru: "Сон в чашке", en: "Nap in a Cup" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 753, h: 1000,
  },
  {
    slug: "115-guardian-at-the-gate",
    title: { ru: "Страж у ворот", en: "Guardian at the Gate" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 753, h: 1000,
  },
  {
    slug: "116-sentinel-of-the-walls",
    title: { ru: "Дозорная у стен", en: "Sentinel of the Walls" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 753, h: 1000,
  },
  {
    slug: "117-forest-embrace",
    title: { ru: "Лесное объятие", en: "Forest Embrace" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 753, h: 1000,
  },
  {
    slug: "118-fairy-and-the-white-cat",
    title: { ru: "Фея и белый кот", en: "The Fairy and the White Cat" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 753, h: 1000,
  },
  {
    slug: "119-toy-guard",
    title: { ru: "Игрушечная гвардия", en: "Toy Guard" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 800, h: 380,
  },
  {
    slug: "120-embrace-in-armor",
    title: { ru: "Объятие в латах", en: "Embrace in Armor" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 800, h: 1000,
  },
  {
    slug: "121-swamp-gentleman",
    title: { ru: "Болотный джентльмен", en: "Swamp Gentleman" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 560, h: 1000,
  },
  {
    slug: "122-daughter-of-the-river",
    title: { ru: "Дочь реки", en: "Daughter of the River" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 800, h: 1000,
  },
  {
    slug: "123-morning-at-the-window",
    title: { ru: "Утро у окна", en: "Morning at the Window" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 800, h: 1000,
  },
  {
    slug: "124-the-purple-sorcerer",
    title: { ru: "Пурпурный колдун", en: "The Purple Sorcerer" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 800, h: 1000,
  },
  {
    slug: "125-the-little-caravan",
    title: { ru: "Маленький караван", en: "The Little Caravan" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 800, h: 1000,
  },
  {
    slug: "126-weathered-wanderer",
    title: { ru: "Суровый странник", en: "Weathered Wanderer" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 560, h: 1000,
  },
  {
    slug: "127-lady-in-the-top-hat",
    title: { ru: "Дама в цилиндре", en: "Lady in the Top Hat" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 753, h: 1000,
  },
  {
    slug: "128-autumn-walk",
    title: { ru: "Осенняя прогулка", en: "Autumn Walk" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 800, h: 533,
  },
  {
    slug: "129-neon-blade",
    title: { ru: "Клинок из неона", en: "Neon Blade" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 800, h: 1000,
  },
  {
    slug: "130-steel-mohawk",
    title: { ru: "Стальной ирокез", en: "Steel Mohawk" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-21",
    w: 800, h: 1000,
  },
  {
    slug: "131-three-graces",
    title: { ru: "Три грации", en: "Three Graces" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-22",
    w: 800, h: 380,
  },
  {
    slug: "132-dance-of-the-muses",
    title: { ru: "Танец муз", en: "Dance of the Muses" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-22",
    w: 475, h: 1000,
  },
  {
    slug: "133-the-witch-and-the-unicorn",
    title: { ru: "Ведьма и единорог", en: "The Witch and the Unicorn" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-22",
    w: 475, h: 1000,
  },
  {
    slug: "134-mandrake-spirit",
    title: { ru: "Дух мандрагоры", en: "Mandrake Spirit" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-22",
    w: 667, h: 1000,
  },
  {
    slug: "135-at-the-burrows-door",
    title: { ru: "У дверей норы", en: "At the Burrow's Door" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-22",
    w: 560, h: 1000,
  },
  {
    slug: "136-the-alligator-dandy",
    title: { ru: "Аллигатор-денди", en: "The Alligator Dandy" },
    tags: { ru: ["фэнтези-арт"], en: ["fantasyart"] },
    showcase: false,
    dateAdded: "2026-07-22",
    w: 560, h: 1000,
  },
  {
    slug: "137-street-duo",
    title: { ru: "Уличный дуэт", en: "Street Duo" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-22",
    w: 667, h: 1000,
  },
  {
    slug: "138-rowing-at-sunset",
    title: { ru: "Гребля на закате", en: "Rowing at Sunset" },
    tags: { ru: ["стрит-арт"], en: ["streetart"] },
    showcase: false,
    dateAdded: "2026-07-22",
    w: 800, h: 533,
  },
  {
    slug: "139-fast-food-queen",
    title: { ru: "Королева фастфуда", en: "Fast Food Queen" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-22",
    w: 560, h: 1000,
  },
  {
    slug: "140-red-legion",
    title: { ru: "Красный легион", en: "Red Legion" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-22",
    w: 560, h: 1000,
  },
  {
    slug: "141-dark-preacher",
    title: { ru: "Тёмный проповедник", en: "Dark Preacher" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-22",
    w: 560, h: 1000,
  },
  {
    slug: "142-spawn-of-the-streets",
    title: { ru: "Порождение улиц", en: "Spawn of the Streets" },
    tags: { ru: ["киберпанк"], en: ["cyberpunk"] },
    showcase: false,
    dateAdded: "2026-07-22",
    w: 560, h: 1000,
  },
];

// Пути к изображениям
function showcaseSrc(slug) { return `assets/works/showcase/${slug}.webp`; }
function previewSrc(slug) { return `assets/works/gallery/preview/${slug}.webp`; }
function fullSrc(slug) { return `assets/works/gallery/full/${slug}.webp`; }
